name: Selenium Test

on:
  workflow_dispatch:
  push:
    branches: [main]
  schedule:
    - cron: '0 9 * * *'

jobs:
  build-and-test:
    runs-on: windows-latest

    steps:
      - name: Set up JDK 8
        uses: actions/setup-java@v1
        with:
          java-version: '8'

      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Install Chocolatey
        run: |
          Set-ExecutionPolicy Bypass -Scope Process -Force; iex ((New-Object System.Net.WebClient).DownloadString('https://chocolatey.org/install.ps1'))

      - name: Install Specific Chrome Version
        run: choco install googlechrome --version 116.0.5845.86 -y

      - name: Install Specific Chromedriver Version
        run: |
          Invoke-WebRequest -Uri "https://edgedl.me.gvt1.com/edgedl/chrome/chrome-for-testing/116.0.5845.96/win32/chromedriver_win32.zip" -OutFile 'chromedriver_win32.zip'
          Expand-Archive -Path 'chromedriver_win32.zip' -DestinationPath 'C:\Automation\chromedriver_win32'
          Remove-Item -Path 'chromedriver_win32.zip'

      - name: Build with Maven
        run: mvn clean compile

      - name: Run Selenium tests
        run: mvn test
